### ISSUE TITLE
Add type definitions to methods and classes 

### ISSUE THREAD

**Issue by Andrew-Clappison** [GriffithsLab/whobpyt#111]

**Comment by kevinkadak** [comment]
Odd issue right now where the check for the params argument is seemingly evaluating against an instance of ParamsJR(), rather than ParamsJR (the latter of which properly compares, as per some testing in colab)

**Comment by kevinkadak** [comment]
Solved.  Comparing with the class 'ParamsJR' was assessing the incorrect 'local' path of the class; needed to be ParamsJR.ParamsJR, akin to 'ndarray' rather than 'np.ndarray'.

**Comment by Andrew-Clappison** [comment]
Implemented in classes relevant to example 002r and 003r, new issue for adding to other classes in the future.
