### ISSUE TITLE
Replicating Tepfit in WhoBPyT as an example

### ISSUE THREAD

**Issue by Andrew-Clappison** [GriffithsLab/whobpyt#117]
Can make figures as methods later potentially

**Comment by Andrew-Clappison** [comment]
Postponed to later in Nov/Dec.

**Comment by Davi1990** [comment]
Made the code but struggling with importage 

https://colab.research.google.com/drive/10W2jh3dQ8UcEgAwrvvlAlDlMEAGI9S_S?usp=sharing

**Comment by Davi1990** [comment]
Due by next week!

**Comment by Davi1990** [comment]
Done just refining stuffs: 

- check typos 
- cite eLife paper/PyTepFit repo etc.
