### ISSUE TITLE
Add a `LinearNMM` class to `models.py` with 2 methods

### ISSUE THREAD

**Issue by tmorshed** [GriffithsLab/whobpyt#21]
- [This](https://github.com/GriffithsLab/whobpyt/blob/main/whobpyt/models.py) is our file.
-  `_init__(num_regions, SC)`
- `forward(init_state, sim_len, step_size, use_noise)`:
   - Implementing the Euler-Maruyama method
   - without the `tanh`.
   - `params`: initialize with laplacian (can be defaulted as `rand` > transformed into laplacian, but the whole thing as an optional input).

**Comment by tmorshed** [comment]
- [ ]

**Comment by P-Oveisi** [comment]
Implemented as first phase of #27 as class `models.LinearRNN_Params`
