### ISSUE TITLE
Priority (AC) - GPU Support

### ISSUE THREAD

**Issue by tmorshed** [GriffithsLab/whobpyt#28]
Standardize GPU functionality across classes

**Comment by Andrew-Clappison** [comment]
Prototypes have worked, but not top priority

**Comment by Andrew-Clappison** [comment]
Implemented GPU Support for FNG-FPG Fitting and found that it was actually slower. Considering implementing GPU support in a new Batch Fitting Class, in that case it should be faster.

**Comment by Andrew-Clappison** [comment]
Code profiler did not reveal something to improve, but will continued to be used in the future.  

Implemented a Batch Fitting Class with GPU Support. 

Found that running on The Alliance Canada GPUs was much faster than laptop GPU and caused a significant speedup when preforming FIC on Batched Version. 

Need to try FNG-FPG on The Alliance Canada GPUs too.

**Comment by Andrew-Clappison** [comment]
FNG-FPG on The Alliance Canada GPUs was faster, though improvement not as great as with Batch Fitting. 

Added GPU support to Model Fitting. 

Added GPU support to Example 002r.

**Comment by Andrew-Clappison** [comment]
Example which shows GPU vs CPU speed, but not run as part of CI
