### ISSUE TITLE
Adding Robinson power spectrum model to whobpyt

### ISSUE THREAD

**Issue by tmorshed** [GriffithsLab/whobpyt#67]
- Equations from "Multiscale 2005"
- Low priority
  - after the time domain is implemented and improved

**Comment by Andrew-Clappison** [comment]
Will be looked at in a few months

**Comment by Andrew-Clappison** [comment]
We will have a meeting on Thursday

**Comment by Davi1990** [comment]
We are closing this since @JohnWangDataAnalyst is submitting a PR

**Comment by Davi1990** [comment]
We are closing this since @JohnWangDataAnalyst is submitting a PR #141
